### ISSUE TITLE
Transaction spamming issue and transaction PoW

### ISSUE THREAD

**Issue by ngeojiajun** [xolentum/xolentum#11]
Recently, our network is spammed by a lot of transactions and it caused some serious performance issue on the daemons.
Due to that, I suggest to implement a PoW mechanism in transactions to stop the spammers.

Details:
A new field will be added into the transaction body either by adding a new member to the structure directly or add a mandatory field in "extra" field.
When a transaction about to be sent over the network, send need to ensure the transaction hash are below the difficulty (fixed low).
In multisig situation, this refers to the peer that will relay the transaction to the network.

Algorithm: CryptoNight

Suggested difficulty: 1000

Please leave your opinions under the comment

**Comment by wrkzdev** [comment]
My suggestion to keep at least between 1,000-5,000 diff if you are going to do with `CryptoNight`.

**Comment by ngeojiajun** [comment]
Current status:

PoW implementation:
1.  A nonce field will be introduced in transaction block itself
2.  A flag introduced for failed PoW verification
3.  Full PoW will be `cn_slow_hash(pruned_tx)`

PoW integration:
1.  Mempool and Blockchain functions that deal with raw tx has been hooked with the checks
2.  RPC server has been updated for it to reject the invalid PoW with correct flags and message

Chain upgrade:
1. Two phrase fork will be used
2. In V3 fork the tx with valid PoW (tx version 2) will be accepted as valid tx 
3. In V4 fork the PoW will be mandatory (all v1 tx will rejected after this fork)

**Comment by ngeojiajun** [comment]
Implementation completed. See commit 51ee91dbbe059a2b29cea11471499d0de04a5631

**Comment by sohamb03** [comment]
All tests passed, transaction PoW successfully implemented into core, thanks Sakura. Closing this issue.
